[project]
name = "datathon"
version = "1.0.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    # core
    "numpy<2",
    "pandas",
    "matplotlib",
    "seaborn",
    "plotly",
    "scikit-learn",
    "scikit-image",
    "tqdm",
    "h5py",
    # deep learning
    "torch==2.2.2",
    "torchvision==0.17.2",
    "transformers>=4.40,<5",
    "accelerate",
    "timm",
    "albumentations",
    "segmentation-models-pytorch",
    # geospatial
    "rasterio",
    "geopandas",
    "shapely",
    "rioxarray",
    "pyproj",
    "fiona",
    # tambahan
    "ydata-profiling",
    "kagglehub",
    "terratorch>=1.1",
    "pystac-client>=0.9.0",
    "planetary-computer>=1.0.0",
    "stackstac>=0.5.1",
    "xarray>=2026.4.0",
    "dask>=2026.3.0",
    "earthengine-api>=1.7.24",
    "torchgeo",
    "ipykernel>=7.2.0",
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torchvision = [{ index = "pytorch-cu121" }]
torch = { path = "C:/Users/Ratuayu Nurfajar/Downloads/torch-2.2.2+cu121-cp311-cp311-win_amd64.whl" }
